name: deploy_release
on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Checkout ilw-hero
      uses: actions/checkout@v4
      with:
        repository: 'web-illinois/ilw-hero'
        ref: 'main'
        path: './external-directory'
    - run: cp ./external-directory/builder/*.json ./site/imported_json/components
    - run: cp ./external-directory/builder/versions/*.json ./site/imported_json/component_versions
    - run: rm -r ./external-directory

    - name: Checkout ilw-back-to-top
      uses: actions/checkout@v4
      with:
        repository: 'web-illinois/ilw-back-to-top'
        ref: 'main'
        path: './external-directory'
    - run: cp ./external-directory/builder/*.json ./site/imported_json/components
    - run: cp ./external-directory/builder/versions/*.json ./site/imported_json/component_versions
    - run: rm -r ./external-directory

    - name: Checkout ilw-content
      uses: actions/checkout@v4
      with:
        repository: 'web-illinois/ilw-content'
        ref: 'main'
        path: './external-directory'
    - run: cp ./external-directory/builder/*.json ./site/imported_json/components
    - run: cp ./external-directory/builder/versions/*.json ./site/imported_json/component_versions
    - run: rm -r ./external-directory

    - name: Checkout ilw-page
      uses: actions/checkout@v4
      with:
        repository: 'web-illinois/ilw-page'
        ref: 'main'
        path: './external-directory'
    - run: cp ./external-directory/builder/*.json ./site/imported_json/components
    - run: cp ./external-directory/builder/versions/*.json ./site/imported_json/component_versions
    - run: rm -r ./external-directory

    - name: Checkout ilw-columns
      uses: actions/checkout@v4
      with:
        repository: 'web-illinois/ilw-columns'
        ref: 'main'
        path: './external-directory'
    - run: cp ./external-directory/builder/*.json ./site/imported_json/components
    - run: cp ./external-directory/builder/versions/*.json ./site/imported_json/component_versions
    - run: rm -r ./external-directory

    - name: Checkout ilw-grid
      uses: actions/checkout@v4
      with:
        repository: 'web-illinois/ilw-grid'
        ref: 'main'
        path: './external-directory'
    - run: cp ./external-directory/builder/*.json ./site/imported_json/components
    - run: cp ./external-directory/builder/versions/*.json ./site/imported_json/component_versions
    - run: rm -r ./external-directory

    - name: Checkout ilw-breadcrumbs
      uses: actions/checkout@v4
      with:
        repository: 'web-illinois/ilw-breadcrumbs'
        ref: 'main'
        path: './external-directory'
    - run: cp ./external-directory/builder/*.json ./site/imported_json/components
    - run: cp ./external-directory/builder/versions/*.json ./site/imported_json/component_versions
    - run: rm -r ./external-directory
    
    - name: Checkout ilw-video
      uses: actions/checkout@v4
      with:
        repository: 'web-illinois/ilw-video'
        ref: 'main'
        path: './external-directory'
    - run: cp ./external-directory/builder/*.json ./site/imported_json/components
    - run: cp ./external-directory/builder/versions/*.json ./site/imported_json/component_versions
    - run: rm -r ./external-directory

    - name: Checkout ilw-card
      uses: actions/checkout@v4
      with:
        repository: 'web-illinois/ilw-card'
        ref: 'main'
        path: './external-directory'
    - run: cp ./external-directory/builder/*.json ./site/imported_json/components
    - run: cp ./external-directory/builder/versions/*.json ./site/imported_json/component_versions
    - run: rm -r ./external-directory
    
    - name: Checkout ilw-accordion
      uses: actions/checkout@v4
      with:
        repository: 'web-illinois/ilw-accordion'
        ref: 'main'
        path: './external-directory'
    - run: cp ./external-directory/builder/*.json ./site/imported_json/components
    - run: cp ./external-directory/builder/versions/*.json ./site/imported_json/component_versions
    - run: rm -r ./external-directory

    - name: Checkout ilw-tabs
      uses: actions/checkout@v4
      with:
        repository: 'web-illinois/ilw-tabs'
        ref: 'main'
        path: './external-directory'
    - run: cp ./external-directory/builder/*.json ./site/imported_json/components
    - run: cp ./external-directory/builder/versions/*.json ./site/imported_json/component_versions
    - run: rm -r ./external-directory

    - name: Checkout ilw-statistic
      uses: actions/checkout@v4
      with:
        repository: 'web-illinois/ilw-statistic'
        ref: 'main'
        path: './external-directory'
    - run: cp ./external-directory/builder/*.json ./site/imported_json/components
    - run: cp ./external-directory/builder/versions/*.json ./site/imported_json/component_versions
    - run: rm -r ./external-directory

    - name: Checkout ilw-call-to-action
      uses: actions/checkout@v4
      with:
        repository: 'web-illinois/ilw-call-to-action'
        ref: 'main'
        path: './external-directory'
    - run: cp ./external-directory/builder/*.json ./site/imported_json/components
    - run: cp ./external-directory/builder/versions/*.json ./site/imported_json/component_versions
    - run: rm -r ./external-directory

    - name: Checkout ilw-page-title
      uses: actions/checkout@v4
      with:
        repository: 'web-illinois/ilw-page-title'
        ref: 'main'
        path: './external-directory'
    - run: cp ./external-directory/builder/*.json ./site/imported_json/components
    - run: cp ./external-directory/builder/versions/*.json ./site/imported_json/component_versions
    - run: rm -r ./external-directory

    - name: Checkout ilw-pagination
      uses: actions/checkout@v4
      with:
        repository: 'web-illinois/ilw-pagination'
        ref: 'main'
        path: './external-directory'
    - run: cp ./external-directory/builder/*.json ./site/imported_json/components
    - run: cp ./external-directory/builder/versions/*.json ./site/imported_json/component_versions
    - run: rm -r ./external-directory

    - name: Checkout ilw-quote
      uses: actions/checkout@v4
      with:
        repository: 'web-illinois/ilw-quote'
        ref: 'main'
        path: './external-directory'
    - run: cp ./external-directory/builder/*.json ./site/imported_json/components
    - run: cp ./external-directory/builder/versions/*.json ./site/imported_json/component_versions
    - run: rm -r ./external-directory

    - name: Checkout ilw-spacer
      uses: actions/checkout@v4
      with:
        repository: 'web-illinois/ilw-spacer'
        ref: 'main'
        path: './external-directory'
    - run: cp ./external-directory/builder/*.json ./site/imported_json/components
    - run: cp ./external-directory/builder/versions/*.json ./site/imported_json/component_versions
    - run: rm -r ./external-directory

    - name: Checkout ilw-section-nav
      uses: actions/checkout@v4
      with:
        repository: 'web-illinois/ilw-section-nav'
        ref: 'main'
        path: './external-directory'
    - run: cp ./external-directory/builder/*.json ./site/imported_json/components
    - run: cp ./external-directory/builder/versions/*.json ./site/imported_json/component_versions
    - run: rm -r ./external-directory

    - name: Checkout ilw-icon
      uses: actions/checkout@v4
      with:
        repository: 'web-illinois/ilw-icon'
        ref: 'main'
        path: './external-directory'
    - run: cp ./external-directory/builder/*.json ./site/imported_json/components
    - run: cp ./external-directory/builder/versions/*.json ./site/imported_json/component_versions
    - run: rm -r ./external-directory
    
    - name: Checkout toolkit management
      uses: actions/checkout@v4
      with:
        repository: 'web-illinois/toolkit-management'
        ref: 'main'
        path: './external-directory'
    - run: cp ./external-directory/global-css/builder/*.json ./site/imported_json/components
    - run: cp ./external-directory/global-css/builder/versions/*.json ./site/imported_json/component_versions
    - run: rm -r ./external-directory

    - name: NPM Install
      run: npm install
    - run: npm rebuild
    - run: npm run-script build
      env:
        PATH_PREFIX: toolkit-builder-3
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '_site'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
